### ISSUE TITLE
release pre-built binaries to npm

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/watcher#10]
I don't know how to do this

**Comment by devongovett** [comment]
possibly https://github.com/mapbox/node-pre-gyp

**Comment by mischnic** [comment]
https://www.npmjs.com/package/prebuild was recommended to me. It also has more active development

**Comment by mischnic** [comment]
Do we need 32 bit versions?

**Comment by devongovett** [comment]
hmmm... not sure

**Comment by devongovett** [comment]
guess it wouldn't hurt but we'd need to figure out how to get azure to build them. I think the hosted build agents they provide are 64 bit. maybe cross compiling?

**Comment by devongovett** [comment]
This is done already.
