### ISSUE TITLE
setting `parcel serve --cache-dir /dev/null` segfaults the watcher

### ISSUE THREAD

**Issue by benkenawell** [parcel-bundler/watcher#105]
running `parcel serve src/index.html --no-cache --cache-dir /dev/null` on a Macbook gives me a SIGSEGV error code, returning 1.  Since I'm not reading from the cache, I don't understand why this would break parcel.  I believe this is an issue with the watcher given the error code, but I don't have the tools to investigate further.

**Comment by mischnic** [comment]
The cache directory is still used to send data between worker threads. So you shouldn't do `--cache-dir /dev/null` in any case.

In your case, `snapshotPath` would be something like `/dev/null/.281293afed` which is indeed invalid:
https://github.com/parcel-bundler/watcher/blob/caf372c41abff401a60dde698891631e3387ee77/README.md?plain=1#L28-L30
