### ISSUE TITLE
2.1.0 Release hangs on subscribing

### ISSUE THREAD

**Issue by arciisine** [parcel-bundler/watcher#126]
With the latest 2.1.0 release, 
```javascript
require("@parcel/watcher").subscribe(process.cwd(), console.log); 
console.log("Registered");
````
The "Registered" message never appears.  I've tried this in many different folders (wondering if symlinks were at play as it originally appeared in an monorepo.  The result across a new install, versus the monorepo, was the same: the code never  printed "Registered".

Pinning the version back to 2.0.7 has resolved the issue for the time being, but it looks like the new ignore glob support may have introduced some bugs.

**Comment by mischnic** [comment]
What OS are you on (and does `process.cwd()` contain any special letters)? That snippet works fine for me on macOS

**Comment by arciisine** [comment]
I'm running Ubuntu 22.04

```
$ uname -ar
Linux serenity 5.14.0-1054-oem #61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by arciisine** [comment]
Closing, as it looks like forcing the uninstall/reinstall has allowed 2.1.0 to start working again.  This persisted across multiple removals of node_modules, so most likely related to a bad state in the npm cache

**Comment by arciisine** [comment]
@mischnic So the issue arose again, but on 2.0.7 this time.  It looks like I was potentially hitting the limit of available inotify watchers on linux.  It would be great to see an an error message in this scenario versus hanging.

**Comment by mischnic** [comment]
I'm not very familiar with inotify, but there's apparently also sometimes an error in this kind of situation: https://parceljs.org/features/development/#linux%3A-no-space-left-on-device
Not sure if that's different to your case
