### ISSUE TITLE
Separate packages for precompiled binaries

### ISSUE THREAD

**Issue by rtsao** [parcel-bundler/watcher#143]
Both [lightningcss](https://github.com/parcel-bundler/lightningcss) and [esbuild](https://github.com/evanw/esbuild) publish prebuilt binaries as individual npm packages which are declared as `optionalDependencies`. This technique allows package managers to skip downloading the binaries for irrelevant architectures/platforms.

It would be great if @parcel/watcher used the same approach. The current method is a [hurdle for projects](https://github.com/vitejs/vite/issues/13593#issuecomment-1602089765) seeking to minimize the size/cost of dependencies.

I think a sensible starting place might be the GitHub Actions workflows for lightningcss or esbuild. Happy to help contribute

Related:
- https://github.com/yarnpkg/berry/issues/3317
- https://github.com/evanw/esbuild/issues/789
- https://github.com/vitejs/vite/issues/13593

**Comment by devongovett** [comment]
Yes, this has been on my list for a long time, but I haven't had time to work on it. If you're interested, it would be an awesome contribution!
