### ISSUE TITLE
npm ci cannot locate a prebuild for any given architecture

### ISSUE THREAD

**Issue by sputnik-adam** [parcel-bundler/watcher#151]
I'm currently having an issue developing a build pipeline for an application my team has developed and is being packaged with parcel.

When building the application for the first time locally, if I begin with `npm ci` and then build the app, the following error is thrown:

```
Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-darwin-x64. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
```

I can get round this in my local environment by running `npm install` instead, after which `npm ci` works fine.

I can't (and shouldn't) do this in the GitHub Action that is building and deploying the application, though. There, I want to use `npm ci` only, so that the only thing that happens is the dependencies are installed as specified in `package-lock.json`. Unfortunately, the same issue presents itself:

```
Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-linux-x64-glibc. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
```

In each case the build instruction is:

```bash
parcel build src/index.tsx --no-cache --no-content-hash --no-source-maps --dist-dir build
```

It feels like there's either an issue with parcel/watcher's use with `npm ci` or some undocumented arcana here for behaviour that I haven't encountered before. If this isn't a real issue with parcel/watcher, any assistance in understanding the issue would be appreciated.

Thanks

Here is a copy of `package.json` in case that has some relevant information

```json
{
  "name": "svg-colour-picker",
  "version": "0.1.0",
  "private": true,
  "output": "svg-colour-picker",
  "dependencies": {
    "@tanstack/react-query": "^4.32.0",
    "async-retry": "^1.3.3",
    "axios": "^1.4.0",
    "clsx": "^2.0.0",
    "http-status-codes": "^2.2.0",
    "react": "^18.2.0",
    "react-device-detect": "^2.2.3",
    "react-dom": "^18.2.0",
    "react-inlinesvg": "^3.0.2",
    "sleep-promise": "^9.1.0",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "^2.9.3",
    "@parcel/transformer-svg-react": "^2.9.3",
    "@parcel/transformer-typescript-tsc": "^2.9.3",
    "@parcel/validator-eslint": "^2.9.3",
    "@tanstack/react-query-devtools": "^4.32.0",
    "@types/async-retry": "^1.4.5",
    "@types/node": "^20.4.4",
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@types/retry": "^0.12.2",
    "@types/uuid": "^9.0.2",
    "@typescript-eslint/eslint-plugin": "^5.62.0",
    "@typescript-eslint/parser": "^5.62.0",
    "buffer": "^6.0.3",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.33.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "http-server": "^14.1.1",
    "husky": "^8.0.3",
    "parcel": "^2.9.3",
    "parcel-resolver-tspaths": "^0.0.9",
    "posthtml-cli": "^0.10.0",
    "posthtml-insert-at": "^0.2.7",
    "posthtml-remove-tags": "^0.1.0",
    "prettier": "^2.8.8",
    "process": "^0.11.10",
    "stylelint": "^15.10.2",
    "stylelint-config-standard-scss": "^10.0.0",
    "stylelint-order": "^6.0.3",
    "typescript": "^4.9.5"
  },
  "scripts": {
    "start": "sh ./scripts/start.sh",
    "build": "sh ./scripts/build.sh",
    "static": "sh ./scripts/static.sh",
    "lint": "eslint --max-warnings=0 src && stylelint 'src/**/*.scss'",
    "lint:fix": "eslint --fix && stylelint --fix '**/*.scss'",
    "format": "prettier --write './**/*.{js,jsx,ts,tsx,css,md,json}' --config ./.prettierrc",
    "prepare": "husky install"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "last 2 versions",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by lanesawyer** [comment]
I saw this pop up for me today too. It's weird, as it only happens for this one specific branch where the only changes are adding a new tool ([Betterer](https://phenomnomnominal.github.io/betterer/)) in the `package.json` and not all the other CI builds for different feature branches.

I did get around it by adding the following to `optionalDependencies`: `"@parcel/watcher-linux-x64-glibc": "2.2.0"`.

You might have some luck adding `@parcel/watcher-darwin-x64: "2.2.0"` to your `optionalDependencies`

**Comment by sputnik-adam** [comment]
Thank you @lanesawyer this did resolve the issue for me for now.

Quick note for anyone else who comes across this issue using Parcel in a CI workflow, you may also be about to run into another similar issue which I hope I can save you some time on:

- [https://github.com/parcel-bundler/parcel/issues/9100]

This was resolved by explicitly installing `lightningcss` with `npm install lightningcss`, causing `package-lock.json` to be updated with the architecture-specific dependencies.

**Comment by nunof07** [comment]
Thank you @lanesawyer and @sputnik-adam, those tips are lifesavers.

`npm ci` wasn't working on GitHub Actions. I ended up adding this to package.json:

```
  "optionalDependencies": {
    "@parcel/watcher-linux-x64-glibc": "2.2.0",
    "lightningcss-linux-x64-gnu": "1.21.5"
  },
```
