### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by undefinedbuddy** [parcel-bundler/watcher#16]
Are there any hopes for TypeScript support?

Thumbs up for this awesome file watcher, by the way!

**Comment by DeMoorJasper** [comment]
It's only one JS file, probably makes little sense to make the build process more complex for just that one file.
You could just add a type definition file?
Contribute it to this repo or definitelyTyped and it should be good.
We're using Flow for Parcel Core so I guess if there would be types here it'd be Flow.
