### ISSUE TITLE
Allow to consume with C++ sources to build as part of `npm install`

### ISSUE THREAD

**Issue by bpasero** [parcel-bundler/watcher#191]
I think ever since https://github.com/parcel-bundler/watcher/commit/062bca4887f17a2f448c11a99bfc2f826eb98c3e, components that depend on `@parcel/watcher` no longer compile the module from its C++ sources but get prebuild versions.

In VS Code we require to build C++ modules from sources, so it would be great to have the ability back to do so, so that we can move to newer versions of this module.

I think a starting point is to have the sources back in the NPM package: https://github.com/parcel-bundler/watcher/pull/157

Alternatively, maybe a different NPM package could be published that is strictly for building from sources?

//cc @devongovett

**Comment by devongovett** [comment]
We may be able to publish the source files. The thing I'd be worried about and need to look into is whether including the `binding.gyp` causes npm to always build from source rather than using the prebuilds, and if there is a way to avoid that.

**Comment by deepak1556** [comment]
Hi! I believe npm will build following the default `install` script logic since this package does not override one since https://github.com/parcel-bundler/watcher/pull/144. An idea could be to override the `install` script section that checks if `process.env.npm_config_build_from_source` set and proceeds to run `node-gyp rebuild` command otherwise do nothing.

**Comment by tmm1** [comment]
What's the simplest cross-platform solution for conditional npm script?

>"install":"node -e \"if (process.env.npm_config_build_from_source) require('child_process')...

**Comment by deepak1556** [comment]
You can take https://github.com/prebuild/node-gyp-build/blob/master/bin.js as an example. Basically what we want is,

```
if (buildFromSource()) {
  build()
}
```

**Comment by deepak1556** [comment]
Thanks @devongovett 🚀
