### ISSUE TITLE
Unable to install parcel@next without internet access

### ISSUE THREAD

**Issue by boyeborg** [parcel-bundler/watcher#26]
# 🐛 bug report

I'm unable to install `parcel@next` on a computer without internet access.
At work, I do most of my work in an air gapped network (i.e. no internet connection). I usually install NPM packages by copying them over to a local NPM registry within our air gapped network, and then installing them as normal (npm/yarn install whatever). This worked for parcel v1, but does no longer work for parcel v2.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
npm i -g parcel@next
```

## 🤔 Expected Behavior

Parcel gets installed on the computer.

## 😯 Current Behavior

It stops at the `@parcel/watcher` trying to run `prebuild-install -r napi || node-gyp rebuild`. Since the computer doesn't have internet access, prebuild-install fails with an error, and the installation gets cancelled.

**Comment by mischnic** [comment]
We should investigate just including the binaries in the npm tarball (regarding file size).
