### ISSUE TITLE
Do not compile native bindings on install

### ISSUE THREAD

**Issue by countcretinos** [parcel-bundler/watcher#30]
As discussed [here](https://github.com/parcel-bundler/parcel/issues/3377#issuecomment-599207281).

>  I agree 100% running that on install isn't a good solution. Feel free to open an issue here: https://github.com/parcel-bundler/watcher I might look into it when I have some time, already did this for the source-maps cpp package so it should be fairly straightforward to also do it for the watcher

**Comment by ranisalt** [comment]
I can't install @parcel/watcher on AArch64 and I think this is related, as there is no prebuilt binaries for this architecture and the install script is unable to build from source.

Logs aren't helpful, though:
```
error /home/rsa/frontend/node_modules/@parcel/watcher: Command failed.
Exit code: 127
Command: prebuild-install -r napi || node-gyp rebuild
Arguments: 
Directory: /home/rsa/frontend/node_modules/@parcel/watcher
```

**Comment by mischnic** [comment]
Do you get more details if you go into `/home/rsa/frontend/node_modules/@parcel/watcher` and execute `npx prebuild-install -r napi` or `npx node-gyp rebuild` manually?

I'm not sure how good node-gyp's ARM support is...

**Comment by ranisalt** [comment]
If I go inside the folder, I don't get the error. It builds fine with `node-gyp rebuild`.

Will try using yarn link.
