### ISSUE TITLE
Ignore option not working in getEventsSince

### ISSUE THREAD

**Issue by rtsao** [parcel-bundler/watcher#35]
```js
const path = require("path");
const watcher = require("@parcel/watcher");

(async () => {
  let cwd = process.cwd();
  let opts = {
    ignore: [path.join(cwd, "node_modules")],
  };

  let subscription = await watcher.subscribe(
    cwd,
    (err, events) => {
      console.log("events", events);
    },
    opts
  );

  let events = await watcher.getEventsSince(cwd, "snapshot.txt", opts);
  console.log("eventsSince", events);
})();
```

Editing `node_modules` is correctly ignored by the subscription, but `getEventsSince` is still returning events for `node_modules`.

- `@parcel/watcher@2.0.0-alpha.5`
- macOS 10.15.3

**Comment by DeMoorJasper** [comment]
Actually just noticed today that our CI has been consistently reporting the same issue, might've been a change in fsevents or something, it used to work when alpha.5 was released...
