### ISSUE TITLE
Publish new version to NPM

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/watcher#45]
This allows the removal of the `flow-libs` entry in Parcel core. [Also necessary for #5297](https://github.com/parcel-bundler/parcel/pull/5297#issuecomment-718454938).

**Comment by DeMoorJasper** [comment]
Released as `2.0.0-alpha.9` thanks for the reminder

**Comment by 101arrowz** [comment]
@DeMoorJasper Sorry I haven't checked this in a few weeks but actually the published version is missing flow and TS types...
