### ISSUE TITLE
memory leak on Linux

### ISSUE THREAD

**Issue by KyleAMathews** [parcel-bundler/watcher#55]
I noticed that @parcel/watcher has a memory leak that affects Linux (I've tested Linux and MacOS).

This is most noticeable once you watch a larger number of pages. My [reproduction](https://github.com/KyleAMathews/parcel-watcher-memory-leak-reproduction) has 10k. 

If you loop over writing a snapshot, creating/modifying a file in the watched directory, and then getting events, rss will increase a consistent amount through each loop.

For ~10k files, it's roughly 4.2mb / loop. The amount increases/decrease linearly with the number of files. The memory increase is all in rss but not on the heap which makes me suspect it's held in the native extension.

On MacOS there's a one time increase in the amount of memory but then doesn't increase no matter how many times you run the loop.

Happy to dig in further or help in other ways.

Great package! We like it a lot at Gatsby.

**Comment by KyleAMathews** [comment]
FYI, we can work around this for now by running @parcel/watcher in a child process so the memory gets cleaned up everytime. It's surprisingly fast! Only a ~50ms overhead for starting the node process.

**Comment by devongovett** [comment]
Hey thanks for the report! I'll take a look soon.
