### ISSUE TITLE
Support simple glob patterns for ignore rules

### ISSUE THREAD

**Issue by bpasero** [parcel-bundler/watcher#64]
This is a feature request to enhance the `ignore` option to support simple glob patterns. 

As an example, I recently came across this PR for `nsfw` that discusses such support for their library: https://github.com/Axosoft/nsfw/pull/124

Bottom line: ignore patterns are very important on Linux at least, because of the operating system global limit of opened file handles, so you really need to exclude folders from the file watcher to not run into issues with opening too many file handles. Having support for glob patterns in the ignore option would mean, clients could define a pattern such as `**/node_modules` and have that work regardless of the folder they are in.

**Comment by devongovett** [comment]
Glob patterns would indeed be useful! There are two ways we could implement them. The simplest approach is to do it in JavaScript, as there are already lots of glob libraries out there. No operating system API supports passing globs directly, so we will have to filter after receiving events anyway.

The other way would be to do it in C++. The benefit there would be performance. Since watching occurs on a background thread, we wouldn't overwhelm the JS thread with events that will be ignored anyway. However, implementing glob matching from scratch sounds hard. Perhaps there are some C++ libraries that implement globbing, though I also wouldn't want to bring in a large library if it has the potential for security issues. I suppose we could use Rust for the glob matching... 🤔 

Any thoughts on that from your perspective?

**Comment by bpasero** [comment]
@devongovett unfortunately the JavaScript approach wouldn't be a good solution for VS Code at least: for Linux it is important to apply the ignore rules at the level of where folders are recursively resolved and added to be watched. Since Linux has a natural upper limit of opened file handles, the ignore pattern is the only way for Linux users to avoid hitting that limit (related issue: https://github.com/microsoft/vscode/issues/40898). 

VS Code is already filtering the events on the receiving end but I would much prefer a native solution in C++ within the watcher. 

Btw I am not necessarily saying you need full glob support to achieve this. Even VS Code itself implements a [simple glob library](https://github.com/microsoft/vscode/blob/77905c850e170eab00cac5ca190c7b1fe5ad43ba/src/vs/base/common/glob.ts#L1) that supports patterns such as `**` and `*` but not everything the spec allows you to do. It is optimised for performance by avoiding to run a RegEx for all patterns when patterns [have a specific form](https://github.com/microsoft/vscode/blob/77905c850e170eab00cac5ca190c7b1fe5ad43ba/src/vs/base/common/glob.ts#L232-L238). 

When looking into `nsfw` I noticed this pull request that seems to implement simple globbing in C++: https://github.com/Axosoft/nsfw/pull/124/files?authenticity_token=ifa16H3MpIoYvE3UXvzRn%2FP3eXbU9xziU2OqaQuUTyK99mBonpsX9DPygK%2BJyZCGMgrDUG2aXOne1QvQBXYGtw%3D%3D&file-filters%5B%5D=.cpp&file-filters%5B%5D=.gyp&file-filters%5B%5D=.h&file-filters%5B%5D=.md&file-filters%5B%5D=.ts#diff-7f14a4a5a7200888990f03862d86776107f7825be09854976d56e0760d1d01bb

Maybe that could be used as foundation going forward.

**Comment by devongovett** [comment]
Thanks for the writeup! I think this would be a great feature for you to contribute. 🥳 

In terms of implementation, I like the idea of converting globs to regexes on the JavaScript side and passing them to C++. This only needs to happen once at startup and shouldn't be too expensive performance wise. JS glob libraries are widely used and well tested, and managing C++ dependencies is much more complex, so I think this is a good approach.

For the API, another option could be to keep the `ignore` option, but allow both paths and globs. We can detect whether each ignore pattern is a glob e.g. using https://github.com/micromatch/is-glob, and perhaps pass them as separate lists to the C++ backend but keep the JS API unified. Would that make sense to you?

**Comment by bpasero** [comment]
What a fantastic idea to convert from JS to RegEx, I was not even thinking about that. We can then just use our existing code to convert from VSCode 💯

**Comment by joaomoreno** [comment]
Lovely, great idea! I also like the API suggestion, I feel like that's actually the minimal API change we'd need and stays aligned with today's API. Given that, what do you think of directly using [`minimatch`'s `makeRe` API](https://github.com/micromatch/micromatch/blob/HEAD/index.js#L387)? That is, assuming JavaScript regular expressions are fairly compatible with C++11's... 🤔

**Comment by mischnic** [comment]
> That is, assuming JavaScript regular expressions are fairly compatible with C++11's... 🤔

There is a ECMAScript std::regex flavour which is also the default if not set explicitly in the constructor: https://en.cppreference.com/w/cpp/regex/syntax_option_type
