### ISSUE TITLE
macOS: copying a file emits a create event for the copied file

### ISSUE THREAD

**Issue by bpasero** [parcel-bundler/watcher#67]
**Steps:**
* setup the watcher to watch on a folder
* from the finder duplicate a file via copy + paste
* 🐛  you get a created event for the file that is being copied

This does not seem to happen when duplicating a folder (that is empty).

**Comment by devongovett** [comment]
Looks like macOS fires an event for the original file with the `kFSEventStreamEventFlagItemCloned` flag in that case: https://developer.apple.com/documentation/coreservices/1455361-fseventstreameventflags/kfseventstreameventflagitemcloned. I think we can safely ignore these events if there are no other flags set.
