### ISSUE TITLE
Watcher does not emit events for rapidly changing file

### ISSUE THREAD

**Issue by bpasero** [parcel-bundler/watcher#70]
(I tested this on macOS and Windows)

Use the following code and notice how no event is being emitted from the watcher:

```js
const watcher = require('@parcel/watcher');
const fs = require('fs');

// Subscribe to events
(async function () {
    let now = Date.now();
    let subscription = await watcher.subscribe('<path to folder>', (err, events) => {
        console.log(err, events);
        now = Date.now();
    }).catch(err => {
        console.error(err);
    });
})();

setInterval(() => {
    fs.writeFileSync('<path to file in folder>', 'Hello World');
}, 10);
```

It looks like the debouncing in the watcher is never allowing to release events but is always catching up with the changes. I would have expected that 1 event is released every debounce interval at least.

**Comment by devongovett** [comment]
Interesting. Yeah the original goal was to prevent emitting changes when lots of different files are changing at once (e.g. git checkout, or npm install), and emit a single event with everything at the end. But I hadn't thought about the case where the same file is changing over and over. Perhaps we can detect that case, or have a second (longer) debounce interval that forces emitting what we have regardless of whether files are continuing to change. I think the current interval of 50ms is probably too short for that.

**Comment by bpasero** [comment]
A similar issue exists when you pipe the output of `ping` to a file:
* Windows: `ping -t 127.0.0.1 > out.txt`
* Posix: `ping 127.0.0.1 > out.txt`

Parcel watcher does not report any change event in this case.

**Comment by MichaelSuen-thePointer** [comment]
Hi everyone. I just found that, if I turn off this option of VSCode's SVN extension (below). VSCode then can refresh changing files as normal.
![POPO20220914-135443](https://user-images.githubusercontent.com/12868093/190071646-3a7a4ee1-86b9-4c10-8f27-d098ce55d068.png)
I don't know this option as anything to do with this issue, if you can invesigate it, it will be a great help. For now, I will just contiune with this option turned off.

**Comment by devongovett** [comment]
Updated this logic in #113, so now there should always be at least one event every 500ms.
