### ISSUE TITLE
Watcher emits delete event for created and then deleted file

### ISSUE THREAD

**Issue by bpasero** [parcel-bundler/watcher#71]
VS Code itself does some event coalescing (see [watcher.ts](https://github.com/microsoft/vscode/blob/a4342f3addc29f405a5cb4aab359b0b98223411e/src/vs/platform/files/node/watcher/watcher.ts#L64)). I think these rules can be pushed down to the watcher itself so that everyone benefits from this.

I would have expected the event coalescing to ignore this case where a file is quickly created and then deleted:

```js
(async function () {
    let subscription = await watcher.subscribe('<path to folder>', (err, events) => {
        console.log(err, events);
    }).catch(err => {
        console.error(err);
    }).then(() => {
        setTimeout(() => {
            fs.writeFileSync('<path to new file in folder>', 'Hello World');
            setTimeout(() => {
                fs.unlinkSync('<path to new file in folder>');
            }, 1);
        }, 1);
    });
})();
```

From my testing on macOS, I get a delete event. Interestingly on Windows I do not get an event as expected.

**Comment by devongovett** [comment]
Unfortunately it's not always possible. macOS does event coalescing of its own. It's possible to receive events with both the create and delete flags set. These flags persist for some time even after an event is delivered (really they are just a hint about what may have happened), so when this happens we have to stat the file. If it doesn't exit we have to assume it was deleted and inform the client. Clients should ignore events for files they are unaware of.

**Comment by bpasero** [comment]
I see, thank you for clarifying. It is probably not a big deal for VS Code.
