### ISSUE TITLE
Why this over native NodeJS watch?

### ISSUE THREAD

**Issue by jakuski** [parcel-bundler/watcher#82]
Hi there,

What advantages does this library bring over NodeJS' native `fs.watch`?

Thank you

**Comment by devongovett** [comment]
`fs.watch` is pretty inconsistent. There is some official documentation about this: https://nodejs.org/docs/latest/api/fs.html#fswatchfilename-options-listener and this section from the chokidar (another watcher library) readme is good: https://github.com/paulmillr/chokidar#why
