### ISSUE TITLE
Any way to use without await/async in top level? Can´t unsubscribe while exiting the program

### ISSUE THREAD

**Issue by leopucci** [parcel-bundler/watcher#90]
Hi. Thanks for your nice work on this lib!
I was wondering if someone could help with using this lib in top level module without await. 

```
  let watcherObj;
  (async () => {
    let subscription = await watcher.subscribe(syncDir, (err, events) => {
      childLogger.info(`CHILD -- EVENTO ANTES: ${safeJsonToString(events)}`);

      childLogger.info(
        `CHILD -- EVENTO DEPOIS: ${safeJsonToString(debounce(events))}`
      );
    });

    childLogger.info('CHILD -- SUBSCRIPTION INICIADA');
    watcherObj = subscription;
  })().catch((e) => {
    childLogger.error(`Error in watcher: ${e}`);
  });

```

I tried something like this, but i am not being able to get back the subscribe result to the main code. 
Any hints?

```
  watcherObj.unsubscribe();
             ^
TypeError: watcherObj.unsubscribe is not a function
```

Can´t unsubscribe while exiting the program.

Thanks
Pucci

**Comment by mischnic** [comment]
You are missing an `await`, it should be `let subscription = await ...` in your example

**Comment by leopucci** [comment]
Hey @mischnic, thanks for your help. 
Indeed I forgot, but I tested here and I am not being able to return the object to the main code even with the await. 
I also tried some sort of callback. And I am going to try some event sending.

**Comment by mischnic** [comment]
I've just tried this and it works correctly (exists after 2 seconds without an error):

```js
const watcher = require('@parcel/watcher');

let watcherObj;
(async () => {
  let subscription = await watcher.subscribe(__dirname, (err, events) => {
    console.log(`CHILD -- EVENTO DEPOIS:`, events);
  });

  console.log('CHILD -- SUBSCRIPTION INICIADA');
  watcherObj = subscription;
})().catch((e) => {
  console.log(`Error in watcher: ${e}`);
});

setTimeout(() => {
  watcherObj.unsubscribe();
}, 2000);
```

**Comment by leopucci** [comment]
Wow. Thank you Niklas @mischnic for your wise attention. 

Using setTimeout worked like a charm. 
I used an old sleep style function that didn´t let the variable to be refreshed in time. 

Thanks 🥇
