### ISSUE TITLE
musl (Alpine) prebuild for darwin-arm64

### ISSUE THREAD

**Issue by sampullman** [parcel-bundler/watcher#95]
Currently, when installing a package that depends on `@parcel/watcher` in an Alpine Docker image on my M1 Mac, none of the existing prebuilds match and a rebuild from source is required each time my `node_modules` changes. It also bloats the image size, since g++/make/python is required.

Is it possible to provide a musl prebuild for `darwin-arm64`?

My current workaround is to build `@parcel/watcher` locally for musl and manually copy the whole dependency + extra prebuild to the Dockerfile. It works fine but it would be nice to avoid the hack.

**Comment by richmidwinter** [comment]
Any chance you could share that hack?
